
service:
    type: ClusterIP
    port: 5432
persistence:
    enabled: false

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

initdbScripts:
  initdb.sql: |
     create TABLE trades (transactionId uuid NOT NULL,portfolioId int NOT NULL,symbol VARCHAR(16) NOT NULL,shares INTEGER NOT NULL,price DECIMAL(12,2) NOT NULL,commission DECIMAL(12,2) NOT NULL,notional DECIMAL(12,2) NOT NULL,xactionsrc VARCHAR(32) NOT NULL,xactionts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (transactionId));
