# Default values for trader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
portfolio:
  image:
    repository: clouddragons/portfolio-spring-appmod
    tag: "1.0"
    pullPolicy: Always
    pullSecrets:
stockQuote:
  image:
    repository: clouddragons/stock-quote-liberty
    tag: "1.0"
    pullPolicy: Always
    pullSecrets:
tradeHistory:
  enabled: true
  image:
    repository: clouddragons/trade-history-python
    tag: "1.1"
    pullPolicy: Always
    pullSecrets:
tradr:
  enabled: true
  image:
    repository: clouddragons/tradr-node-jquery-appmod
    tag: "1.0"
    pullPolicy: Always
    pullSecrets:
eventStreamsConsumer:
  enabled: true
  image:
    repository: clouddragons/event-streams-consumer-appmod
    tag: "1.0"
    pullPolicy: Always
    pullSecrets:
ingress:
  host: changeme
